sudo: required
dist: trusty
notification: 
    email: false

before_install:
    - wget -q -O /dev/stdout "https://raw.githubusercontent.com/sunoru/julia-icc-travis/master/install-julia.sh" | bash
    - . ~/.bashrc

script:
    - julia-release-0.4 -e 'Pkg.clone(pwd()); Pkg.test("VML", coverage=true)'

after_success:
    - julia-release-0.4 -e 'cd(Pkg.dir("VML")); Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
